### ISSUE TITLE
New AdBuddiz-3.1.11.jar lib is available

### ISSUE THREAD

**Issue by Astrovic** [m1ga/tiadbuddiz#1]
Hi,
new AdBuddiz-3.1.11.jar lib is available (https://publishers.adbuddiz.com/pub_portal/sdk/java_migration). Could you rebuild the module with this new lib? https://publishers.adbuddiz.com/resources/sdk/AdBuddiz-Java-3.1.11.zip
Thanks :)

**Comment by m1ga** [comment]
Of course! Version 1.3 is online now.
